### ISSUE TITLE
RFC: Set filetype of the result buffer

### ISSUE THREAD

**Issue by rochacbruno** [arjunmahishi/flow.nvim#14]
Hi I have this setting with `Packer` to use https://hurl.dev

```lua
{
    'arjunmahishi/flow.nvim',
    config = function()

      require('flow').setup({
        output = {
          buffer = true,
          split_cmd = '20split',
        },
        filetype_cmd_map = {
          hurl = "echo %s | hurl | jq",
        }
      })
   
    end,
}
```

It works great

![flow_no_ft](https://user-images.githubusercontent.com/458654/210432593-089d5f3d-7b60-4759-be42-3f376a10aa7d.png)

However as you can see my result (which is a valid JSON) has no highlight

I have to manually run `set ft=json`

![flow_json](https://user-images.githubusercontent.com/458654/210432687-fa81b5e8-17ff-4684-abca-7bea6d12066c.png)

I could create an auto_cmd to detect something in the result buffer, but it is a `[No Name]` and I don't know how to detect it.

## What is the feature I am missing?

Option 1

```lua
output = {
    ...,
    post_loading_cmd="set ft=json",
    post_loading_callback = function() vim.api.do_something() end
}
```

Option 2

```lua
autocmd( {"BufEnter"},
    pattern="flow_result_buffer"  -- Does it exist?
)
```

Option 3 - Per command (the best scenario)

```lua
 filetype_cmd_map = {
          hurl = {
               "echo %s | hurl | jq",
               buffer=true,
               split_cmd="20split",
               buffer_name="result",
               buffer_ft="json",
               post_cmd="do something in the new buffer"
        }
```

**Comment by arjunmahishi** [comment]
Hey @rochacbruno, Thanks for reaching out!

I like the idea of supporting syntax highlighting in the output buffer. This would make a great feature

But I am not sure if _coupling the current file type with the output buffer's file type_ is a good Idea (`hurl` = `json`). Because commands can potentially result in any output format.

I was just checking out the unix command [file](https://linux.die.net/man/1/file). Looks like this can be used to **infer** the file type based on the output content. This could be useful.

#### Example

![image](https://user-images.githubusercontent.com/11977524/210486929-b16a9cef-c365-4e57-b735-7569b3119019.png)

---

If **inferring** the file type is not the preferred way, then there could also be an option to override the inferred file type (like in your `option 3`)
